---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume
  namespace: 4labs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 200.100.50.200
    path: /home/suporte/app
