apiVersion: v1
kind: ConfigMap
metadata:
  name: app-example-nginx-templates
data:
  metrics.conf.template:
    server {
      listen 127.0.0.1:8080;
      location /stub_status {
        stub_status on;
      }