apiVersion: v1
kind: Service
metadata:
  name: app-example
  labels:
    app.kubernetes.io/name: app-example
spec:
  selector:
    app.kubernetes.io/name: app-example
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: http-metrics
      port: 9113
      targetPort: http-metrics