apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-persistent-storage
  namespace: 4labs
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 192.168.15.103
    path: /opt/app