---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-nfs-app
  namespace: 4labs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 192.168.15.103
    path: /opt/app
