---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-nfs-mysql
  namespace: 4labs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
#  mountOptions:
#    - hard
#    - nfsvers=4.1
  nfs:
    server: 192.168.15.103
    path: /opt/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-nfs-mysql
  namespace: 4labs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
