apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage
  namespace: 4labs
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 192.168.15.103
    path: /opt/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-nfs-mysql
  namespace: 4labs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi