---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-nfs-app
  namespace: 4labs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
#  mountOptions:
#    - hard
#    - nfsvers=4.1
  nfs:
    server: 192.168.15.3
    path: /opt/app


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-nfs-app
  namespace: 4labs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
