apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage
  namespace: 4labs
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.15.2
    path: /opt/data