apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      operated-prometheus: "true"
  endpoints:
    - port: web
      interval: 10s

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alertmanager
spec:
  selector:
    matchLabels:
      operated-alertmanager: "true"
  endpoints:
    - port: web
      interval: 10s