apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-mysqlapirodrigomoro
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysqlapirodrigomoro
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage-class-mysqlapirodrigomoro
  local:
    path: /mnt/data/mysqlapirodrigomoro
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kube-node2.domain.net

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysqlapirodrigomoro
  namespace: apimysqlapplication
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: storage-class-mysqlapirodrigomoro
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-application-deployment
  namespace: apimysqlapplication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-application
  template:
    metadata:
      labels:
        app: mysql-application
    spec:
      containers:
        - name: mysql-application-container
          image: docker.io/rodrigomoro/mysqlapirodrigomoro:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets-appuser-mysqlapirodrigomoro
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets-appuser-mysqlapirodrigomoro
                  key: mysql-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets-root-mysqlapirodrigomoro
                  key: mysql-root-password
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: pvc-mysqlapirodrigomoro
