apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubespace-persistent-storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # Change to match PVC or vice versa
  persistentVolumeReclaimPolicy: Retain  # Consider using Retain or Delete
  nfs:
    server: 192.168.68.103
    path: /opt/kubescape


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubespace-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
