apiVersion: v1
kind: PersistentVolume
metadata:
  name: argocd-persistent-storage
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # Changed to Retain
  nfs:
    server: 192.168.68.103
    path: /opt/redis


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-argocd-pv-claim
  labels:
    app: redis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
