---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: datadog-agent
  namespace: datadog
spec:
  template:
    spec:
      containers:
        - name: datadog-agent
          env:
            - name: DD_CRI_SOCKET_PATH
              value: /run/containerd/containerd.sock
          volumeMounts:
            - name: containerdsocket
              mountPath: /run/containerd/containerd.sock
            - mountPath: /host/run
              name: var-run
              readOnly: true
          volumes:
            - hostPath:
                path: /run/containerd/containerd.sock
              name: containerdsocket
            - hostPath:
                path: /run
              name: run
