apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  # Credentials to communicate between:
  #  * Agents and Datadog (API/APP key)
  #  * Node Agent and Cluster Agent (Token)

  global:
    clusterName: kubemoro
    site: us5.datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: API-key
      appSecret:
        secretName: datadog-secret
        keyName: APP-key

  override:
    # Node Agent configuration
    #nodeAgent:
    #  tolerations:
    #    - operator: Exists

    # Cluster Agent configuration
    clusterAgent:
      replicas: 2
  # Enable Features

  features:

    eventCollection:
      collectKubernetesEvents: true
    logCollection:
      enabled: true
      containerCollectAll: true
    usm:
      enabled: true
    npm:
      enabled: true
    kubeStateMetricsCore:
      enabled: true
    kubeStateMetricsCore:
      enabled: true
    liveContainerCollection:
      enabled: true
    orchestratorExplorer:
      enabled: true
    externalMetricsServer:
      enabled: true
      useDatadogMetrics: true
      