apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  template:
    spec:
      containers:
        - name: datadog-agent
          # ...
          env:
            - name: DD_CRI_SOCKET_PATH
              value: /run/containerd/containerd.sock
          volumeMounts:
            - name: containerdsocket
              mountPath: /run/containerd/containerd.sock
            - mountPath: /run
              name: var-run
              readOnly: true
          volumes:
            - hostPath:
                path: /run/containerd/containerd.sock
              name: containerdsocket
            - hostPath:
                path: /run
              name: run
  # Credentials to communicate between:
  #  * Agents and Datadog (API/APP key)
  #  * Node Agent and Cluster Agent (Token)

  global:
    clusterName: kubemoro
    site: us5.datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: API-key
      appSecret:
        secretName: datadog-secret
        keyName: APP-key
    kubelet:
        tlsVerify: false

  override:
    # Node Agent configuration
    nodeAgent:
      tolerations:
        - operator: Exists
    clusterAgent:
      containers:
        cluster-agent:

    # Cluster Agent configuration
    clusterAgent:
      replicas: 4
  # Enable Features

  features:

    eventCollection:
      collectKubernetesEvents: true
    logCollection:
      enabled: true
      containerCollectAll: true
    usm:
      enabled: true
    npm:
      enabled: true
    kubeStateMetricsCore:
      enabled: true
    kubeStateMetricsCore:
      enabled: true
    liveContainerCollection:
      enabled: true
    orchestratorExplorer:
      enabled: true
    externalMetricsServer:
      enabled: true
      useDatadogMetrics: true
    apm:
      enabled: true
      unixDomainSocketConfig:
        path: /var/run/datadog/apm.sock # default
      