apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: datadog
  namespace: datadog
spec:
  channel: stable
  name: datadog-operator
  source: operatorhubio-catalog
  sourceNamespace: datadog
  config:
    resources:
      requests:
        memory: "250Mi"
        cpu: "250m"
      limits:
        memory: "250Mi"
        cpu: "500m"
    env:
      - name: API-key
        valueFrom:
          secretKeyRef: 
             key: API-key
             name: datadog-secret
      - name: APP-key
        valueFrom:
          secretKeyRef: 
            key: APP-key
            name: datadog-secret   
  override:
    clusterAgent:
      image:
        name: gcr.io/datadoghq/cluster-agent:latest
    nodeAgent:
      image:
        name: gcr.io/datadoghq/agent:latest
    clusterAgent:
      replicas: 4
    nodeAgent:
      tolerations:
        - operator: Exists

 