apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-persistent-storage
  namespace: 4labs
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # Change to match PVC or vice versa
  persistentVolumeReclaimPolicy: Retain  # Consider using Retain or Delete
  nfs:
    server: 192.168.68.103
    path: /opt/app
