---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-nfs-mysql
  namespace: 4labs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.15.102
    path: /opt/data
